import './globals.css';
import { AppProviders } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <AppProviders>
        <body className="dark:bg-zinc-900 dark:text-white bg-zinc-50 text-black h-full">
          {children}
        </body>
      </AppProviders>
    </html>
  );
}
